# Generated by Django 6.0.2 on 2026-02-07 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Template identifier (e.g., 'welcome', 'password_reset')", max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Use {{variable}} for dynamic content', max_length=255)),
                ('html_content', models.TextField(help_text='HTML email content. Use {{variable}} for dynamic content')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version (optional)')),
                ('description', models.TextField(blank=True, help_text='What this template is used for')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive templates won't be used")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_email', '-created_at'], name='email_logs_to_emai_5b10dd_idx'), models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx')],
            },
        ),
    ]
